### ISSUE TITLE
I can't gon on compiling your project

### ISSUE THREAD

**Issue by jackrun2000** [pelya/commandergenius#1]
I followed your instruction and compiled your project, but stopped while compiling project/jni/freetype/builds/amiga/src/base/ftdebug.c with many include file missing errors, such as exec/types.h, utility/tagitem.h, and so on. I searched for a long time and couldn't find how to get them. Please tell me a way to compile your project successfully. I use ubuntu with android-ndk-r4.

**Comment by pelya** [comment]
It sohuld not build files from freetype/builds dir, it should only use freetype/src. Seems that the "find" command in your environment worked with some errors and added extra dirs. Can you please add to freetype/Android.mk line:
$(info APP_SUBDIRS $(APP_SUBDIRS))
after the "APP_SUBDIRS := ....." line, and give me the output.
Also tell me what OS are you using.

**Comment by jackrun2000** [comment]
My OS is Ubuntu 10.04, kernel is 2.26.32. I compile it in project directory, use ndk-build -j2 V=1. After add $(info APP_SUBDIRS $(APP_SUBDIRS)), the results as before, there are so many -Idirectory, then appear: /home/jack/Desktop/pelya/commandergenius/project/jni/../jni/application/src/project/jni/freetype/builds/amiga/src/base/ftdebug.c:51:24: error: exec/types.h: No such file or directory,..., many error like this. I think if you want to compile ftdebug.c, the include files will be not forbidden.

**Comment by pelya** [comment]
Have no idea about that - I'm using Ubuntu 10.04 too, and it compiles fine for me. Just delete the freetype/builds directory to force it compile.

**Comment by jackrun2000** [comment]
I download your newest project and pass the compile successfully, then I run it in emulator, android AVD set 2.2. After completing load some files from sourceforge, the project quit without any prompt. If run it again, the word "Change phone configuration" flash once then quit anyway. I wonder if the project can be run in emulator or not, or there is something wrong in my environment setting.

**Comment by pelya** [comment]
Do you mean LBreakout2 game? It's still work in progress, however it worked somehow when I was running it on my phone. What does it write to logcat when crashes?

**Comment by jackrun2000** [comment]
the logcat show below after some .so loaded:
I/AndroidRuntime(  289): AndroidRuntime onExit calling exit(0)
I/ActivityManager(   67): Process net.sourceforge.lgames.lbreakout2 (pid 289) has died.
I/WindowManager(   67): WIN DEATH: Window{43fc6f58 net.sourceforge.lgames.lbreakout2/net.sourceforge.lgames.lbreakout2.MainActivity paused=false}
I/WindowManager(   67): WIN DEATH: Window{43f6c2c8 SurfaceView paused=false}
I/WindowManager(   67): Setting rotation to 0, animFlags=1
I/ActivityManager(   67): Config changed: { scale=1.0 imsi=310/260 loc=en_US touch=3 keys=2/1/2 nav=3/1 orien=1 layout=18 uiMode=17 seq=5}
I/UsageStats(   67): Unexpected resume of com.android.launcher while already resumed in net.sourceforge.lgames.lbreakout2
W/InputManagerService(   67): Got RemoteException sending setActive(false) notification to pid 289 uid 10033
D/dalvikvm(  124): GC_EXTERNAL_ALLOC freed 943 objects / 41576 bytes in 152ms
D/dalvikvm(   67): GC_EXPLICIT freed 1203 objects / 63752 bytes in 193ms

but when I run SC2 on emulator, it is OK.

**Comment by pelya** [comment]
I've told you - lbreakout2 does not work yet. Did you intend to launch SC2 instead? I guess you've forgot to run ChangeAppSettings.sh script after you've changed symlink to SC2 sources. Also I recommend you to clean up objs/application dir to make clean build.

**Comment by jackrun2000** [comment]
Yes, I did, and launched SC2 on emulator and real machine.

**Comment by pelya** [comment]
I guess I may close this one
