### ISSUE TITLE
Combine GLSurfaceView_SDL variant with Android defined view

### ISSUE THREAD

**Issue by faywong** [pelya/commandergenius#14]
Hi Buddy,
    I have extended your GLSurfaceView_SDL and combine it with Android MediaController which is a FrameLayout.
But it seems that when GLSurfaceView_SDL don't have actual content the MediaController is displayed, once there
comes a drawing picture request from native code(Such as from a specific SDL_main routine) the Android defined
MediaController disappeared. 
    Do you have any similar try to combine these? What's the expected behavior of it?

**Comment by faywong** [comment]
And I look into this issue more deeply and found that GLSurfaceView_SDL can't receive onKeyDown/onKeyUp callbacks given by Android. It seems that all the input event from touch-screen is intercepted by SDL totally. This is the root cause of my above issue. Any suggestion to me?

**Comment by pelya** [comment]
Easiest will be to modify method dispatchTouchEvent inside MainActivity, if you want to intercept touch events.
onKeyDown/onKeyUp are also defined inside MainActivity, but they will react only on physical key, such as Back button.

**Comment by faywong** [comment]
Got it. Many thanks.
