### ISSUE TITLE
"powered by" logo

### ISSUE THREAD

**Issue by caiiiycuk** [pelya/commandergenius#15]
I had done porting one of the classic game, and i think it is good idea to add logo of you project.

Do you have such logos?

**Comment by pelya** [comment]
You mean, this one? https://github.com/pelya/commandergenius/blob/sdl_android/project/res/drawable/publisherlogo.png

**Comment by caiiiycuk** [comment]
I replace this logo with my own game logo, and in right corner of my logo i add "powered by sdl", should i add something like "powered by  pelya/commandergenius".

Also, do you think about renaming project to sdl-android (or something else)?

**Comment by pelya** [comment]
"powered by pelya/commandergenius"? Seriusly? That will look atrociously.
Project name will stay the same, because I'm too lazy to update hyperlinks everywhere.
