### ISSUE TITLE
Why can't i prevent the a thread exited without detaching from JVM

### ISSUE THREAD

**Issue by faywong** [pelya/commandergenius#16]
Hi Pelya,

In my latest commit [1](https://github.com/faywong/FFPlayer_SDL), i created a pthread_key_t [2](https://github.com/faywong/JNIContextHelper)for threads that created in Java layer, to do a automatically detaching from JVM when the thread exits.

I verified this way works fine in my other JNI related project.

Have your meet the same issue(crashed when a thread created in Java layer & exited from native code without formerly detaching from JVM)?

Just as the typical log:
437 07-28 11:55:45.989  9615  9652 D dalvikvm: threadid=13: thread exiting, not yet detached (count=0)
438 07-28 11:55:45.989  9615  9652 D dalvikvm: threadid=13: thread exiting, not yet detached (count=1)
439 07-28 11:55:45.989  9615  9652 E dalvikvm: threadid=13: native thread exited without detaching
440 07-28 11:55:45.989  9615  9652 E dalvikvm: VM aborting
441 07-28 11:55:45.989  9615  9652 F libc    : Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 9652 (GLThread)
442 07-28 11:55:46.020   437   476 D KeyguardUpdateMonitor: Lawmo lock is mLawmoLock=false
443 07-28 11:55:46.028 10275 10322 D AudioHardwareMot: Output latency, from ALSA = 99
444 07-28 11:55:46.051 10275 10322 D AudioHardwareMot: Output latency, from ALSA = 99
445 07-28 11:55:46.075 10275 10322 D AudioHardwareMot: Output latency, from ALSA = 99
446 07-28 11:55:46.098 10275 10322 D AudioHardwareMot: Output latency, from ALSA = 99
447 07-28 11:55:46.114 15784 15784 I DEBUG   : **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
448 07-28 11:55:46.114 15784 15784 I DEBUG   : Build fingerprint: 'motorola/XT910_cn/umts_spyder:4.1.2/6.7.2_GC-381/398:user/release-keys'
449 07-28 11:55:46.114 15784 15784 I DEBUG   : pid: 9615, tid: 9652, name: GLThread  >>> org.ffmpeg.ffplayer <<<
450 07-28 11:55:46.114 15784 15784 I DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadd00d
451 07-28 11:55:46.122 10275 10322 D AudioHardwareMot: Output latency, from ALSA = 99
452 07-28 11:55:46.145 10275 10322 D AudioHardwareMot: Output latency, from ALSA = 99
453 07-28 11:55:46.176 10275 10322 D AudioHardwareMot: Output latency, from ALSA = 99
454 07-28 11:55:46.614 15784 15784 I DEBUG   : tls: 5580af00
455 07-28 11:55:46.614 15784 15784 I DEBUG   : 
456 07-28 11:55:46.614 15784 15784 I DEBUG   :     r0 00000000  r1 4081265c  r2 deadd00d  r3 000000ff
457 07-28 11:55:46.614 15784 15784 I DEBUG   :     r4 40812656  r5 0000020c  r6 40138460  r7 00000001
458 07-28 11:55:46.614 15784 15784 I DEBUG   :     r8 407d7a2d  r9 40138454  sl 5136afc0  fp 00000001
459 07-28 11:55:46.614 15784 15784 I DEBUG   :     ip 00001f00  sp 5580ac20  lr 407cb00f  pc 407cb01e  cpsr 80000030
460 07-28 11:55:46.614 15784 15784 I DEBUG   :     d0  74726f6261204d75  d1  6977206465746973
461 07-28 11:55:46.614 15784 15784 I DEBUG   :     d2  6568636174656465  d3  746e756f63282072
462 07-28 11:55:46.614 15784 15784 I DEBUG   :     d4  3ff0000000000000  d5  0000000000000000
463 07-28 11:55:46.614 15784 15784 I DEBUG   :     d6  3ff0000000000000  d7  3ff0000000000000
464 07-28 11:55:46.614 15784 15784 I DEBUG   :     d8  7ff8000000000000  d9  412e848000000000
465 07-28 11:55:46.614 15784 15784 I DEBUG   :     d10 0000000000000000  d11 0000000000000000
466 07-28 11:55:46.614 15784 15784 I DEBUG   :     d12 0000000000000000  d13 0000000000000000
467 07-28 11:55:46.614 15784 15784 I DEBUG   :     d14 0000000000000000  d15 0000000000000000
468 07-28 11:55:46.614 15784 15784 I DEBUG   :     d16 3ff0000000000000  d17 7e37e43c8800759c
469 07-28 11:55:46.614 15784 15784 I DEBUG   :     d18 3f964134a0a972e0  d19 c0256370281281e3

Thanks,
faywong

**Comment by pelya** [comment]
No, I did not get this issue, because typical SDL application does not care
what happens after main() returns, so I'm calling exit(0) which gracefully
terminates the whole process.
BTW the license of these files isn't compatible to LGPL:
MARVELL RESERVES THE RIGHT AT ITS SOLE
DISCRETION TO REQUEST THAT THIS CODE BE IMMEDIATELY RETURNED TO MARVELL.

**Comment by faywong** [comment]
Thanks for your clarifying. The issue i ran across may be is related to the implement of SDL_QUIT(just before exit(0)), I'll look into it more deeply.
The license used in JNIContextHelper will be change to LGPL. Thanks for your reminding.
