### ISSUE TITLE
Problems on video 'adreno 320'

### ISSUE THREAD

**Issue by caiiiycuk** [pelya/commandergenius#18]
I use 8bpp SDL_SWSURFACE | SDL_HWPALETTE video mode, and i have some problems with adreno 320: game hangs up on devices with this video.

Problem devices:

```
    Google
        Nexus 4– mako
        Nexus 10– manta
    HTC
        HTC One– m7
    Huawei
        MTC Viva– hwu8816
        HUAWEI U9508– hwu9508
    LGE
        LG-E615– m4ds
    Samsung
        Galaxy S 4– jflte
        Galaxy S4 LTE A– ks01lteskt
        Galaxy S4– jflteMetroPCS
        Galaxy S 4– jaltektt
    Sony Ericsson
        Xperia Z – SO-02E
        Xperia Z– C6603
        Xperia ZL– C6502
        Xperia Z– C6606
    Нет данных
        SGP321
```

Common cases:

```
Just downloaded last night. I have a stock Sprint HTC One. When the game starts up, it hangs as soon as I touch the screen. Cannot start a game even it that menu comes up.
```

```
Device: Samsung Galaxy s4 i9505.
Trouble: When open application on few moments see splashscreen. After only black screen and google advertisment top of screen. Advertisment work. Android think that application work. But no reaction on screen click.
```

```
I have galaxy s4. Game starts and then freezes with Westwood logo in background.

Been waiting for the whole dune series to end up on Android. Now it's here and it doesn't work. Very frustrating. I see many others complaining about the same thing.

I was hoping with this latest update it would be fixed. But it not.
```

**Comment by pelya** [comment]
That's strange, SW video mode should work everywhere. I don't have any of those devices, so unfortunately I cannot help here. I'll try to gain access to one of these, but that will take some time.

**Comment by caiiiycuk** [comment]
Problem can be reproduced in Samsung Remote Test lab on Galaxy S4. For now i have this log when app start:

VERBOSE|08-24 13:15:53.547|24953|24953||SDL|GLSurfaceView_SDL::onPause()
INFO|08-24 13:15:53.547|24953|24953||libSDL|OpenGL context lost - sending SDL_ACTIVEEVENT
INFO|08-24 13:15:53.647|24953|24953||SDL|libSDL: onWindowFocusChanged: false - sending onPause/onResume
INFO|08-24 13:16:07.951|25332|25332||SDL|libSDL: Creating startup screen
INFO|08-24 13:16:08.271|25332|25332||SDL|libSDL: onWindowFocusChanged: true - sending onPause/onResume
DEBUG|08-24 13:16:08.421|25332|25360||dalvikvm|No JNI_OnLoad found in /data/data/com.gamesinjs.dune2/files/../lib/libsdl_mixer.so 0x4209c990, skipping init
INFO|08-24 13:16:08.421|25332|25360||SDL|libSDL: Loading libraries
INFO|08-24 13:16:08.421|25332|25360||SDL|libSDL: loading lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl_mixer.so
DEBUG|08-24 13:16:08.421|25332|25360||dalvikvm|Trying to load lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl_mixer.so 0x4209c990
INFO|08-24 13:16:08.421|25332|25360||SDL|libSDL: loaded GLESv2 lib
INFO|08-24 13:16:08.421|25332|25360||SDL|libSDL: Trying to extract binaries from assets binaries.zip
DEBUG|08-24 13:16:08.421|25332|25360||dalvikvm|Added shared lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl-1.2.so 0x4209c990
INFO|08-24 13:16:08.421|25332|25360||SDL|libSDL: loading lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl-1.2.so
INFO|08-24 13:16:08.421|25332|25332||SDL|libSDL: Settings.Load(): enter
DEBUG|08-24 13:16:08.421|25332|25360||dalvikvm|Added shared lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl_mixer.so 0x4209c990
INFO|08-24 13:16:08.421|25332|25360||SDL|libSDL: Loading settings
DEBUG|08-24 13:16:08.421|25332|25360||dalvikvm|Trying to load lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl-1.2.so 0x4209c990
INFO|08-24 13:16:08.421|25332|25360||SDL|libSDL: Trying to extract binaries from assets binaries-armeabi-v7a.zip
INFO|08-24 13:16:08.551|25332|25332||SDL|libSDL: Settings.Load(): loaded settings successfully
INFO|08-24 13:16:08.551|25332|25360||SDL|libSDL: Timeout reached in startup screen, process with downloader
DEBUG|08-24 13:16:08.551|25332|25360||dalvikvm|Trying to load lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl_main.so 0x4209c990
INFO|08-24 13:16:08.551|25332|25360||SDL|libSDL: loading lib /data/data/com.gamesinjs.dune2/files/../lib/libapplication.so
INFO|08-24 13:16:08.551|25332|25332||SDL|libSDL: old cfg version 92, our version 92
INFO|08-24 13:16:08.551|25332|25360||SDL|libSDL: loading lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl_main.so
DEBUG|08-24 13:16:08.551|25332|25360||dalvikvm|No JNI_OnLoad found in /data/data/com.gamesinjs.dune2/files/../lib/libsdl_main.so 0x4209c990, skipping init
INFO|08-24 13:16:08.551|25332|25360||SDL|libSDL: Starting data downloader
DEBUG|08-24 13:16:08.551|25332|25360||dalvikvm|Added shared lib /data/data/com.gamesinjs.dune2/files/../lib/libsdl_main.so 0x4209c990
INFO|08-24 13:16:08.561|25332|25332||SDL|libSDL: Starting downloader
INFO|08-24 13:16:08.661|25332|25332||SDL|libSDL: Initializing video and SDL application
VERBOSE|08-24 13:16:08.752|25332|25371||SDL|GLSurfaceView_SDL::EglHelper::start(): creating GL context
VERBOSE|08-24 13:16:08.802|25332|25371||SDL|GLSurfaceView_SDL::EGLConfigChooser::chooseConfig(): selected 0: R5G6B5A0 depth 0 stencil 0 type 71 (GLES GLES2 OPENVG) caveat none nr 0 pos 0 (0,0,0,0,0)
VERBOSE|08-24 13:16:08.852|25332|25371||SDL|GLSurfaceView_SDL::EglHelper::createSurface(): creating GL context
INFO|08-24 13:16:08.862|25332|25371||SDL|libSDL: DemoRenderer.onSurfaceChanged(): paused false mFirstTimeStart false w 1920 h 1080
INFO|08-24 13:16:08.862|25332|25371||SDL|libSDL: DemoRenderer.onSurfaceCreated(): paused false mFirstTimeStart true
INFO|08-24 13:16:08.892|25332|25371||libSDL|Calling SDL_main(" -d data-en/")
INFO|08-24 13:16:08.892|25332|25371||SDL|libSDL: setting envvar LANGUAGE to 'en_GB'
DEBUG|08-24 13:16:08.892|25332|25371||SDL|libSDL: Is running on OUYA: false
VERBOSE|08-24 13:16:08.912|25332|25371||libSDL|SDL_SetVideoMode(): Requested mode: 640x400x8, obtained mode 640x400x16
INFO|08-24 13:16:08.912|25332|25371||libSDL|SDL_SetVideoMode(): application requested mode 640x400 OpenGL 0 HW 0 BPP 16
INFO|08-24 13:16:08.912|25332|25371||libSDL|SDL_Mixer: Timidity: cannot find timidity.cfg, MIDI support disabled
VERBOSE|08-24 13:16:08.912|25332|25371||libSDL|SDL_SetVideoMode(): returning surface 0x72b9ad68
VERBOSE|08-24 13:16:08.912|25332|25371||libSDL|calling SDL_SetVideoMode(640, 400, 8, 536870912)
INFO|08-24 13:16:08.912|25332|25371||libSDL|ANDROIDAUD_OpenAudio(): app opened audio bytespersample 2 freq 22050 channels 1 bufsize 1024, SDL returns bufsize 1024

Does this log have something interesting?

**Comment by pelya** [comment]
I did not know Samsung provides free remote test services, that's interesting.
Does it log anything more? This log is kind of short, but I do not see any errors.
I've asked a user to test OpenTTD on Nexus 4, and he reported that OpenTTD works fine, while Dune freezes.
It uses same video settings, the only difference is that it does not have ads.
Could you please upload your AndroidAppSettings.cfg somewhere?

**Comment by caiiiycuk** [comment]
For now i use this settings:
http://play-dune.com/AndroidAppSettings.cfg
Also i know that SDL_UpdateRect often called.

I will try to localize problem.

**Comment by pelya** [comment]
Yes, the only difference is that in OpenTTD ads are disabled.
I've tried to move advertisement initialization later in the code, I don't know if that can help.

**Comment by caiiiycuk** [comment]
I just found that problem is in implementation of interval timers (`setitimer`). By some reasons it does not work on samsung devices. I think that this bug is not related with SDL port. So i close this issue. Thanks for help.

**Comment by caiiiycuk** [comment]
https://github.com/caiiiycuk/dunedroid/issues/17
