### ISSUE TITLE
Playing midi files through SDL_mixer

### ISSUE THREAD

**Issue by caiiiycuk** [pelya/commandergenius#19]
It is possible to play .mid files through Mix_PlayMusic in android? In native app its work as expected. But when i build android app i dont hear music. Also i implement sound effects through Mix_PlayChannel and they work in native app and android app.

Maybe i miss something?

Also, this files i can play through Android Media Player and it is work fine.

**Comment by caiiiycuk** [comment]
Code:

```
void Music_Play(uint16 musicID)
{
    Mix_Music *toPlay;

    char musicFile[256];
    sprintf(musicFile, "music/opendune_%d.mid", musicID);

    if (File_Exists_Dir(musicFile, "")) {
        toPlay = Mix_LoadMUS(musicFile);
        Error("Should play %s, %d\n", musicFile, toPlay);
        Mix_PlayMusic(toPlay, 0);
    } else {
        Error("Not found %s\n", musicFile);
    }

    return;
```

**Comment by pelya** [comment]
There are Timidity and FluidSynth ports in SDL repository (OpenTTD uses Timidity), you'll need an additional instruments sound pack to use them. sdl_mixer also uses timidity, but I should check if it's working. Anyway, you'll need to download and unpack this file into your app working dir (just add it to AndroidAppSettings.cfg): http://sourceforge.net/projects/libsdl-android/files/timidity.zip/download

**Comment by pelya** [comment]
SDL_mixer can play MIDI files just fine - check out "testmidi" sample app in SDL repository.

**Comment by caiiiycuk** [comment]
Thanks it is worked!
