### ISSUE TITLE
Surface error

### ISSUE THREAD

**Issue by webpolis** [pelya/commandergenius#28]
Hi

I know this may not have anything to do with your particular code, but I'm really needing help here. I'm porting a SDL 1.2 game, using your repo as base, and i'm getting the following error on SDL_SetVideoMode:

04-01 10:37:36.006  15620-15719/com.webpolis.game.soccerkup V/libSDL﹕ calling SDL_SetVideoMode(800, 480, 32, -1879048192)
04-01 10:37:36.006  15620-15719/com.webpolis.game.soccerkup I/libSDL﹕ SDL_SetVideoMode(): application requested mode 800x480 OpenGL 0 HW 0 BPP 32
04-01 10:37:36.006  15620-15719/com.webpolis.game.soccerkup E/libSDL﹕ ERROR: Setting the swap interval is not supported
04-01 10:37:36.006  15620-15719/com.webpolis.game.soccerkup E/libSDL﹕ ERROR: Getting the swap interval is not supported
04-01 10:37:36.006  15620-15719/com.webpolis.game.soccerkup E/libSDL﹕ ERROR: GL_GetAttribute not supported
04-01 10:37:36.006  15620-15719/com.webpolis.game.soccerkup I/libSDL﹕ ANDROID_GL_GetProcAddress("glGetString"): 0x40090cb4
04-01 10:37:36.016  15620-15719/com.webpolis.game.soccerkup V/libSDL﹕ SDL_SetVideoMode(): Requested mode: 800x480x32, obtained mode 800x480x32
04-01 10:37:36.016  15620-15719/com.webpolis.game.soccerkup V/libSDL﹕ SDL_SetVideoMode(): returning surface 0x4f4f0ad0

As you see, the surface is created, but nothing is shown. I'm using existing code, which has been proved to work fine in my desktop. Any way, this error is triggered at the beginning, on initialization, before the game loop.

The piece of code here is:

```
    SDL_SetVideoMode(ww, hh, 32, SDL_SWSURFACE|SDL_ANYFORMAT|SDL_FULLSCREEN);
```

I'm doing **ndk-debug** and the error is triggered after the above line is executed.

In AndroidAppSettings.cfg I have (between other stuff, of course):

```
VideoDepthBpp=32
SwVideoMode=y
SdlVideoResize=y
```

Also, inside the game loop, I had to disable

```
SDL_GL_SwapBuffers();
```

because it was causing _OpenGL video mode has not been set_

Is there anything I should check? I am very new to SDL/OpenGL stuff, but I was successful in getting some of the games included in your package to work on my device.

Thanks in advance, any help is very very appreciated. If successful, I will share my code with you.

**Comment by pelya** [comment]
Seems like your application tries to use OpenGL, and you're setting
software video mode instead - you cannot mix them.
Are you sure your game does not use OpenGL? Can you give me the link to
it's sources?

You need to call SDL_Flip(SDL_GetVideoSurface()) for software surface, or
SDL_GL_SwapBuffers() for OpenGL, otherwise nothing will get drawn on the
screen.

I would also suggest to use 24bpp color depth for software video surface,
I'm not sure if 32bpp will work at all,  and only OpenGL can use alpha
channel of the videobuffer.

**Comment by webpolis** [comment]
Thanks pelya, I can't stop now trying to port this game to android :) I've spent lots of hours, and i'm a tough guy.

I've pushed the code to https://github.com/webpolis/ows-android

Main initialization happens in:
- https://github.com/webpolis/ows-android/blob/master/main.cpp
- https://github.com/webpolis/ows-android/blob/master/game.cpp (where the error happens)

I've been reading the code in the few games I already pushed into my device (biniax and teeworlds) and tried to replicate the initialization as much as possible.

If you can help me to get into the right track, I will send you a quality beer or some other gift.. believe me, I really want this to work.

Thanks men!

**Comment by webpolis** [comment]
Regarding the libs, I've disabled anything related with _boost_ (it wasn't needed for my purposes) and have ported _ftgles_ (libftgl2) successfully.

**Comment by pelya** [comment]
Your game definitely uses OpenGL, this means you have to enable OpenGL in
SDL settings, software mode will not work for you.
Please set:

VideoDepthBpp=24
SwVideoMode=n

and set video mode as following:

SDL_SetVideoMode(ww, hh, 24, SDL_OPENGL|SDL_DOUBLEBUF|SDL_FULLSCREEN);

See file project/jni/application/test-opengl/sdl_hello.cpp - it's a
minimal example of working SDL OpenGL app.

**Comment by pelya** [comment]
And you'll need to call SDL_GL_SwapBuffers() to draw each video frame to
screen.

**Comment by webpolis** [comment]
Oh men, I am an as**ole :) Your tips were great, it helped me to realize about the difference.. I was walking blindly in an unexplored territory. Thanks!

Before I contacted you, I already tried the SDL_OPENGL flag, and I thought I was doing something wrong because my screen was black.. I could only see the "virtual keyboard" graphic.
But, the issue was caused because some variables weren't set, regarding the screen size.

So, I can continue! Thanks!

Do you want the beer?? Send me your details to nico@webpolis.com.ar

Kindest regards

**Comment by webpolis** [comment]
Btw, now I've got your attention, how do I define the keyboard in AndroidAppSettings.cfg? I have **arrow keys** and **period key** (the . character). I can use another, not just the period key, but I still don't understand how to set this in AndroidAppSettings.cfg. I can move my characters around with the onscreen keyboard, but I cannot trigger the **period key**.

I also don't understand the difference between:
- RedefinedKeys
- AppTouchscreenKeyboardKeysAmount
- RedefinedKeysScreenKb

Thanks!

**Comment by pelya** [comment]
Set AppTouchscreenKeyboardKeysAmount=1, RedefinedKeysScreenKb="PERIOD",
and AppNeedsArrowKeys=y.
Deinstall your game before testing, to clean old config files on device.
