### ISSUE TITLE
Middle mouse button emulation

### ISSUE THREAD

**Issue by caiiiycuk** [pelya/commandergenius#29]
Hi this is not really bug, it is a question. It is possible to configure build to emulate middle button with 2 fingers tap? I mean when i touch screen with two fingers sdl will recive mouse middle press with coords of first finger, when i move fingers it will recive mouse move events with middle button pressed, and finally send mouse up event.

If not, what the best way to implement this behaviour. If possible please say what classes should be modified to implement this. I plan to implement this feature if is not yet available.

Thanks.

**Comment by pelya** [comment]
You can send middle button click by touching the screen with three fingers.
If you set RightMouseButtonLongPress=n in AndroidAppSettgins,cfg, you'll be
able to send middle mouse button click without sending right button click.

Relevant code is in
project/jni/sdl-1.2/src/video/android/SDL_androidinput.c in function
ProcessMouseMultitouch(),

just replace SDL_BUTTON_RIGHT with SDL_BUTTON_MIDDLE if you want to
hard-code it.

**Comment by caiiiycuk** [comment]
Thank you very much!
