### ISSUE TITLE
Fails to start on a N7 w/ user profiles

### ISSUE THREAD

**Issue by davidgiven** [pelya/commandergenius#31]
I have a Nexus 7. I'm trying to run Xsdl in a second user profile, but I always receive the message: 'Error: X server failed to launch, because of stale Unix socket with non-existing path.'. Power cycling makes no difference.

I've attached the logs.

I suspect this is because there are hard-coded references to paths which aren't valid in a multiprofile system --- e.g. /data/data/x.org.server/files/usr/share/X11/xkb/rules/evdev; on my device it's at /data/user/10/x.org.server/files/usr/share/X11/xkb/rules/evdev.

I also notice that it's failing to create the Unix socket in /tmp/.X11-unix, because I don't have a /tmp; but don't _all_ Android devices not have a /tmp?

I/libSDL  (14085): Physical screen resolution is 1920x1200
I/SDL     (14085): libSDL: setting envvar LANGUAGE to 'en_GB'
D/SDL     (14085): libSDL: Is running on OUYA: false
I/libSDL  (14085): moveMouseWithGyroscopeSpeed 2 = 5.000000
I/libSDL  (14085): Changing curdir to "/storage/emulated/10/Android/data/x.org.server/files"
I/libSDL  (14085): Calling SDL_main("XSDL")
I/libSDL  (14085): param 0 = "XSDL"
I/XSDL    (14085): Actual video resolution 1920/152x1200/86
I/XSDL    (14085): User u10_a95 ID 1010095
I/XSDL    (14085): Current video mode: 1920 1200
V/libSDL  (14085): calling SDL_SetVideoMode(480, 320, 0, 0)
I/libSDL  (14085): SDL_SetVideoMode(): application requested mode 480x320 OpenGL 0 HW 0 BPP 16
E/libSDL  (14085): ERROR: Setting the swap interval is not supported
E/libSDL  (14085): ERROR: Getting the swap interval is not supported
E/libSDL  (14085): ERROR: GL_GetAttribute not supported
I/libSDL  (14085): ANDROID_GL_GetProcAddress("glGetString"): 0x408ae864
V/libSDL  (14085): SDL_SetVideoMode(): Requested mode: 480x320x16, obtained mode 480x320x16
V/libSDL  (14085): SDL_SetVideoMode(): returning surface 0x758333e8
I/SDL     (14085): Device: flo
I/SDL     (14085): Device name: KTU84L
I/SDL     (14085): Device model: Nexus 7
I/SDL     (14085): Device board: flo
I/System.out(14085): libSDL: input device ID -1 type 769 name Virtual
I/System.out(14085): libSDL: input device ID 1 type 257 name gpio-keys
I/System.out(14085): libSDL: input device ID 2 type -2147483648 name apq8064-tabla-snd-card Headset Jack
I/System.out(14085): libSDL: input device ID 3 type 257 name apq8064-tabla-snd-card Button Jack
I/System.out(14085): libSDL: input device ID 4 type 257 name h2w button
I/System.out(14085): libSDL: input device ID 5 type -2147483648 name lid_input
I/System.out(14085): libSDL: input device ID 6 type 4098 name elan-touchscreen
I/SDL     (14085): AutoDetectTouchInput: hoverTouchDistance 0.0 threshold 552 hover false fingerHover false
I/XSDL    (14085): Screen coords 53 74 res 0
I/XSDL    (14085): Screen coords 183 125 dpi 0
I/XSDL    (14085): TCP port 6000 already used, trying next one: Address already in use
I/XSDL    (14085): 2 network interfaces found
I/XSDL    (14085): interface: lo address: 127.0.0.1
I/XSDL    (14085): interface: wlan0 address: 192.168.148.60
I/XSDL    (14085): XSDL video resolution 1920/152x1200/86x16, args:
I/XSDL    (14085): > XSDL
I/XSDL    (14085): > :1
I/XSDL    (14085): > -nolock
I/XSDL    (14085): > -noreset
I/XSDL    (14085): > -screen
I/XSDL    (14085): > 1920/152x1200/86x16
I/XSDL    (14085): > -exec
I/XSDL    (14085): > /data/user/10/x.org.server/files/usr/bin/xhost + ; /data/user/10/x.org.server/files/usr/bin/xli -onroot -center background.bmp
I/XSDL    (14085): InitConnectionLimits: MaxClients = 255
I/XSDL    (14085): InitCard: (null)
I/XSDL    (14085): Calling SDL_Init()
I/XSDL    (14085): _XSERVTrans
I/XSDL    (14085): mkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
I/XSDL    (14085): _XSERVTrans
I/XSDL    (14085): mkdir: ERROR: Cannot create /tmp/.X11-unix
I/XSDL    (14085): _XSERVTrans
I/XSDL    (14085): SocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 2
I/XSDL    (14085): _XSERVTrans
I/XSDL    (14085): MakeAllCOTSServerListeners: failed to create listener for unix
I/XSDL    (14085): (WW) Failed to open protocol names file /data/data/x.org.server/files/usr/lib/xorg/protocol.txt
I/XSDL    (14085): sdlScreenInit
I/XSDL    (14085): Attempting for 1920x1200/16bpp mode
V/libSDL  (14085): calling SDL_SetVideoMode(1920, 1200, 16, 0)
I/libSDL  (14085): SDL_SetVideoMode(): application requested mode 1920x1200 OpenGL 0 HW 0 BPP 16
E/libSDL  (14085): ERROR: Setting the swap interval is not supported
E/libSDL  (14085): ERROR: Getting the swap interval is not supported
E/libSDL  (14085): ERROR: GL_GetAttribute not supported
I/libSDL  (14085): ANDROID_GL_GetProcAddress("glGetString"): 0x408ae864
V/libSDL  (14085): SDL_SetVideoMode(): Requested mode: 1920x1200x16, obtained mode 1920x1200x16
V/libSDL  (14085): SDL_SetVideoMode(): returning surface 0x758333e8
I/XSDL    (14085): Set 1920x1200/16bpp mode
I/XSDL    (14085): sdlMapFramebuffer: shadow 0
I/XSDL    (14085): sdlRandRInit
I/XSDL    (14085): InitOutput()
I/XSDL    (14085): sdlCreateRes
I/XSDL    (14085): [dix] Could not init font path element /usr/share/fonts/X11/misc/, removing from list!
I/XSDL    (14085): [dix] Could not init font path element /usr/share/fonts/X11/TTF/, removing from list!
I/XSDL    (14085): [dix] Could not init font path element /usr/share/fonts/X11/OTF/, removing from list!
I/XSDL    (14085): [dix] Could not init font path element /usr/share/fonts/X11/Type1/, removing from list!
I/XSDL    (14085): [dix] Could not init font path element /usr/share/fonts/X11/100dpi/, removing from list!
I/XSDL    (14085): [dix] Could not init font path element /usr/share/fonts/X11/75dpi/, removing from list!
I/XSDL    (14085): (EE) XKB: Couldn't open rules file /data/data/x.org.server/files/usr/share/X11/xkb/rules/evdev
I/XSDL    (14085): (EE) XKB: Failed to load keymap. Loading default keymap instead.
I/XSDL    (14085): (EE) XKB: Couldn't open rules file /data/data/x.org.server/files/usr/share/X11/xkb/rules/evdev
I/XSDL    (14085): XKB: Failed to compile keymap
I/XSDL    (14085): Keyboard initialization failed. This could be a missing or incorrect setup of xkeyboard-config.
I/XSDL    (14085): 
I/XSDL    (14085): Fatal server error:
I/XSDL    (14085): Failed to activate core devices.
I/XSDL    (14085): 
I/XSDL    (14085): (dix) removing device 2
I/XSDL    (14085): (dix) removing device 3
I/XSDL    (14085): Current video mode: 1920 1200
V/libSDL  (14085): calling SDL_SetVideoMode(480, 320, 0, 0)
I/libSDL  (14085): SDL_SetVideoMode(): application requested mode 480x320 OpenGL 0 HW 0 BPP 16
E/libSDL  (14085): ERROR: Setting the swap interval is not supported
E/libSDL  (14085): ERROR: Getting the swap interval is not supported
E/libSDL  (14085): ERROR: GL_GetAttribute not supported
I/libSDL  (14085): ANDROID_GL_GetProcAddress("glGetString"): 0x408ae864
V/libSDL  (14085): SDL_SetVideoMode(): Requested mode: 480x320x16, obtained mode 480x320x16
V/libSDL  (14085): SDL_SetVideoMode(): returning surface 0x758333e8

**Comment by pelya** [comment]
Yes, XSDL does not work for non-default user, because it has hardcoded
paths, and this won't change soon, because it's inside legacy Xlib code.
You may ignore the error about /tmp/.X11-unix socket - XSDL creates unnamed
Unix socket, which you can check with
adb shell cat /proc/net/unix | grep X11

**Comment by davidgiven** [comment]
Hmm. The /data/data path is baked into the X server as a compile-time setting, right? Would setting it to a relative path like ./usr/share/X11/xkb/rules/evdev and then having the wrapper program which invokes the server chdir() into the right place be plausible? A quick grep of the X server source shows there's only one instance of chdir(), and it's part of an unused driver...

**Comment by pelya** [comment]
Again not possible, because all configure scripts bitch about relative
paths, and I have very little desire to fix each of them by hand.

**Comment by davidgiven** [comment]
I did actually come up with an evil plan to work around this --- I was going to try, but didn't have time. The secret is that /proc/self/cwd is an absolute path to the current working directory. That would keep configure happy but still allow the X server paths to be set at run time (using the chdir trick).

I did warn you it was evil...

**Comment by pelya** [comment]
Nice idea, I'll try that when I'll have some free time to work on XSDL,
which will probably be in one or two weeks.
I hope SELinux on Lollipop does not block you from reading /proc.

**Comment by pelya** [comment]
Yes it works, I've updated XSDL build files, I'll publish new release this
or next week.

**Comment by davidgiven** [comment]
That's awesome! Slightly disturbing, but awesome!

**Comment by pelya** [comment]
Should be fixed in 1.11.20, feel free to open another bug if it does not work.
