### ISSUE TITLE
XSDL "Change resolution" untouchable resolutions 1024x768 800x600 800x480 640x480

### ISSUE THREAD

**Issue by edgar444** [pelya/commandergenius#33]
In landscape :
Bottom 3rd row is untouchable.
When a resolution is picked it sets the resolution above it instead.

In portrait : 
Right most 3rd column is untouchable.
When a resolution is picked it sets the resolution to the left of it instead.

The following are the resolutions that can't be set :
1024x768 800x600 800x480 640x480

I think it do be better if we could just type in the resolution (& DPI number) inside "Change device configuration"

**Comment by pelya** [comment]
I'll fix that in the next version, probably in two weeks or so.

**Comment by pelya** [comment]
Fixed in 1.11.20

**Comment by sonuydv** [comment]
Sir, web browser is not working.please guide me, what to do for accessing web browser.
