### ISSUE TITLE
Support for Intent x11: scheme (openintents)

### ISSUE THREAD

**Issue by nitomartinez** [pelya/commandergenius#35]
It would be nice if the X11 SDL server supports the

OpenIntents x11:// call

http://www.openintents.org/node/905

Currenty the following xserver already support it:
- xvncpro server https://play.google.com/store/apps/details?id=com.theqvd.android.xpro
- Dark side X Server https://play.google.com/store/apps/details?id=au.com.darkside.XServer

It would be nice if other applications could benefit from the same intent.

**Comment by pelya** [comment]
I'll implement that when I'll have free time, maybe in two weeks or so.

**Comment by nitomartinez** [comment]
Many thanks,

Nito

**Comment by pelya** [comment]
Fixed in 1.11.20. I would like to know which apps can send such intent, because I don't know any.

**Comment by nitomartinez** [comment]
Many thanks for that.

At least it is used by the Android QVD Client.

See http://theqvd.com and https://play.google.com/store/apps/details?id=com.theqvd.android.client

By default it uses the embedded X11 X server https://play.google.com/store/apps/details?id=com.theqvd.android.client

You just need to specify in the connection settings "Use local X" as "generic" instead of "local", and then it will use any application that supports openintents as in

http://www.openintents.org/~oi/node/905

Currently that I know of the QVD client supports
- Xserver SDL
- Xvncpro
- Darkside X server

Many thanks for your help supporting openintents, so that other applications can also support X11 intents.

I will update the documentation 

http://docs.theqvd.com/android.html#_x_server

To include also your X server, which is working really well :-)

**Comment by nitomartinez** [comment]
To correctly get this working it would be nice to have

`
<action android:name="android.intent.action.VIEW>
`
