### ISSUE TITLE
Rebuilding SDL_Sound

### ISSUE THREAD

**Issue by moocow1452** [pelya/commandergenius#36]
I'm trying to build SDL_Sound for Android, specifically, a patched model for MKXP, as it's part of the sound system that the project uses along with fluidsynth etc. (https://github.com/Ancurio/mkxp) This project seems to be one of the better ones for working with SDL_Sound, so I'm wondering if I can use these tools to build SDL_Sound for SDL2, include the patches, and have a library to build other projects with.

**Comment by gerstrong** [comment]
I don't get it, is this some kind of ad?

Commander Genius has nothing to do with MKXP. What do you want to do 
with SDL_Sound anyways. Ever tried SDL_Mixer?

Am 12.11.2014 um 04:51 schrieb moocow1452:

**Comment by moocow1452** [comment]
No, forgive me for being unclear,  but I wanted to know what some of the
build processes were for SDL_Sound since commander genius has Android build
scripts that seem to incorperate it into a bigger SDL.so as opposed to it's
own specifix library.  Do any of you happen to know how that works,  since
MKXP requires an SDL_Sound built around SDL2, and I was having trouble
doing the work from the Android side of the equation.

**Comment by pelya** [comment]
The repository for SDL 1.2 for Android is indeed called commandergenius for
historical reasons, there is another commandergenius repository, with
actual Commander Genius game sources, so a bit of confusion here.

Anyway, it should be enough to copy sdl_sound, flac, ogg, vorbis and mikmod
directories to your repisitory, and edit Android.mk for sdl_sound to remove
SDL version variable. It only uses SDL for basic types, so it should
compile with SDL2. Also, add them to APP_MODULES in your Application.mk,
and don't forget to do System.LoadLibrary() for each of them in correct
order in your Java code.
