### ISSUE TITLE
Porting manual

### ISSUE THREAD

**Issue by st1x51** [pelya/commandergenius#37]
Hello,if you can,please,update and fix porting_manual:)
http://anddev.at.ua/src/porting_manual.txt

**Comment by lubomyr** [comment]
Another porting manual

https://github.com/lubomyr/uae4all2/blob/master/HowToBuild.txt

Only step 4 used for  uae4all2 app.

2014-11-15 18:14 GMT+02:00 st1x51 notifications@github.com:

**Comment by st1x51** [comment]
idk if it helps me, i am newbie in linux
i just want http://www.kristianduske.com/fitzquake/ on andoid

**Comment by pelya** [comment]
There are several open-source Quake 1 ports for Android, for example this
one is fairly complete:
https://play.google.com/store/apps/details?id=com.n0n3m4.Q4A
What differences does fitzquake have over that port?

**Comment by st1x51** [comment]
its clean quake port and easy to modding and compiling under windows

i wrote you on 4pda about qi4a,its very hard engine port for modding and compiling...

**Comment by pelya** [comment]
It will stop being clean and easy once you port it, believe me.

I'm visiting 4pda.ru once per 3 months, please use email or github
bugtracker to contact me.

**Comment by st1x51** [comment]
i thought,it will be easy to port fitz quake with your sdl lib..

can you port this engine? or tell me how to install jdk1.7.0_03 and i'll try to compile your port of rikku2000 port

**Comment by lubomyr** [comment]
try,
apt-get install _openjdk-7-jdk_

2014-11-15 19:58 GMT+02:00 st1x51 notifications@github.com:
