### ISSUE TITLE
lollipop

### ISSUE THREAD

**Issue by davidklevine** [pelya/commandergenius#38]
Both the standalone SDL and Debian noroot give a stale socket error in lollipop so can't be used.

**Comment by pelya** [comment]
I've reproduced this bug on my device, working on a fix.

**Comment by davidklevine** [comment]
Hard to imagine a quicker response than this. Thanks!

----- On 11/18/2014 12:32 pm reply+003e1437e50d31 wrote -----

I've reproduced this bug on my device, working on a fix.

On Tue, Nov 18, 2014 at 4:21 PM, davidklevine notifications@github.com
wrote:

> Both the standalone SDL and Debian noroot give a stale socket error in
> lollipop so can't be used.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pelya/commandergenius/issues/38.

# 

David K. Levine

Professor of Economics and Joint Chair RSCAS
Department of Economics                    http://www.dklevine.com/
European University Institute              phone:  [+39] 055 468 5954
Villa San Paolo                                     office: VSP 45
Via della Piazzuola 43
I-50133 Firenze - Italy

John H. Biggs Distinguished Professor
Department of Economics
Washington University in St. Louis     phone: [+1] 314 935 9529
Campus Box 1208
1 Brookings Dr.
St. Louis MO 63130-4899

**Comment by pelya** [comment]
Should be fixed.
