### ISSUE TITLE
Blocking SDL_Flip() + Accelerometer control => deadlock

### ISSUE THREAD

**Issue by michi42** [pelya/commandergenius#4]
Having some free time again (after several months ...), I adapted the enigma UI for smartphone controls and got the Pause/Resume functionality working. Howewer there is a deadlock if the accelerometer is initialized, the blocking SDL_Flip() behaviour is used and the App ist being paused. In this case, the nativeAccelerometer() call blocks, locking up the whole App.

I did not want to check in changes to the main java source tree after this period of time, but the fix itself is simple - just destroy the accelerometer listener in onPause() and re-initialize it in onResume().

-- Michi

**Comment by pelya** [comment]
Fixed that, thanks
