### ISSUE TITLE
Request for game "Simple Sokoban"

### ISSUE THREAD

**Issue by jasonmacduffie** [pelya/commandergenius#44]
I haven't seen any requests for games to be added, but I also didn't see anything against it either, so I'll shoot.

[Simple Sokoban](http://simplesok.sourceforge.net/) is a fairly bare-bones implementation of Sokoban in ANSI C89, that uses SDL for I/O. I think this would be a great game to be able to play on Android. Since it seems like a simple game (really, there are only four buttons), I am hoping someone would not mind porting it.

**Comment by pelya** [comment]
Simple Sokoban uses SDL2, and I'm porting only games based on SDL 1.2. I
suggest using official SDL2 repository to port this game - it has Android
implementation, however it does not have built-in on-screen keyboard. My
own SDL2 implementation is currently broken.

**Comment by jasonmacduffie** [comment]
Ok thank you for the information. I'll take a look at SDL 2.

**Comment by gerstrong** [comment]
Well, I still have plans to fix that broken support so we could port, but the lack of time is holding me back right now, so sorry...
