### ISSUE TITLE
Milkytracker and Grafx2 issues

### ISSUE THREAD

**Issue by DaDMaN** [pelya/commandergenius#5]
Hi.

I've tested your milkytracker and grafx2 ports for android on my tablet ASUS Transfomer TF101. There are great ports but there isn't support for my keboard+mouse docking. 

Is not possible to configure my docking mouse to work with your programs and gain some precision on grafx2 for example. With milkytracker there are some more problems. It seems not working with my physical keyboard anyway. There aren't any keyboard layout or possible configuration to use my keyboard to compose with the pattern editor.

It will be a GREAT idea and improvement to add physical keyboard and mouse support to your programs to users with tablets with docking extensions (keyboard and mouse) like me.

Great job anyway.

Cheers.

**Comment by pelya** [comment]
I've recompiled with newest SDL and updated packages on Market - that should enable more mouse emulation modes, also I've fixed keyboard issues in Milkytracker.

**Comment by DaDMaN** [comment]
Hi! After updating Grafx2 and MilkyTracker from market, new issues appears on my Asus Transformer.

Asus touchpad still unuseable in both applications (Grafx2 and MilkyTracker). Android system cursor moves at different speed than grafx2 and Milkytracker cursors. It will be a good idea make use of Android system cursor only when using mouse/touchpad configurations. Random pulsations are made too when using touchpad and applications went crazy. Mouse is still not working.

Keyboard layout seems to be ok now in Milkytracker.

New issue with Grafx2: Painting cursor appears now like a big 8x8 white square over the original cursor. Impossible to use it now with mouse or without it (touch mode).
