### ISSUE TITLE
Make SuperTux appear in the OUYA games menu

### ISSUE THREAD

**Issue by cweiske** [pelya/commandergenius#65]
[SuperTux](https://github.com/SuperTux/supertux/) does not appear in the OUYA main menu (games menu), because apps need to follow some rules to appear there:
1. Have a [special intent in the manifest](https://devs.ouya.tv/developers/docs/setup#user-content-developing-with-the-odk): `<category android:name="tv.ouya.intent.category.GAME"/>`
2. An icon `res/drawable-xhdpi/ouya_icon.png` with a size of `732x412`.

Please add that to the SuperTux apk.

**Comment by pelya** [comment]
OUYA is dead, move on.

Razer themselves now sells Android TV box.

**Comment by cweiske** [comment]
I've got an OUYA in my living room and I won't throw it away just because someone else decides that it's dead.

I undestand if you don't want to do additional work for a tiny minority of people, though. Then please close this issue and I'll fix it myself in the latest release .apk.

**Comment by pelya** [comment]
Here you go:
https://sourceforge.net/projects/libsdl-android/files/apk/SuperTux/
I did not test it on OUYA (and I don't have one anyway), so it might not
work.

**Comment by cweiske** [comment]
Thank you - works fine!

![screenshot](http://fotos.cweiske.de/screenshots/2016-10-06%20ouya%20supertux.png)
