### ISSUE TITLE
Update Supertux to version 0.5.0 (stable)

### ISSUE THREAD

**Issue by tobbi** [pelya/commandergenius#66]
Can you update SuperTux to the newly released version 0.5.0? Download from here:
https://github.com/SuperTux/supertux/releases/tag/v0.5.0

If you need anything, don't hesitate to tell us!

**Comment by pelya** [comment]
Will do soon.

**Comment by pelya** [comment]
Done.
The .apk file takes up 99 Mb, so unless Google will increase the file limit again from 100 Mb, I might need to delete some data from the next release, or shrink a few image files. 
I don't want to use expansion files, they are bothersome.
Level editor is obviously broken on Android, I won't be fixing it. 
If you want level editor to be touch-friendly, make every function accessible via a mouse click, and make all buttons bigger.

**Comment by tobbi** [comment]
I created https://github.com/SuperTux/supertux/issues/631 for touch-friendlyness! Thanks!
