### ISSUE TITLE
How to get iconv submodule without checking out every single application?

### ISSUE THREAD

**Issue by nyanpasu64** [pelya/commandergenius#89]
SDL won't compile since the iconv submodule is an empty folder.

How do I checkout all submodule dependencies, but ignore everything in the applications folder? That's very slow.

**Comment by pelya** [comment]
git submodule update --init --recursive

**Comment by nyanpasu64** [comment]
I figured out that you can checkout one folder path at a time, as you encounter empty folders causing compile failures.

running the command without arguments checks out dozens of SDL apps' source code.
