### ISSUE TITLE
Makefile.prebuilt:21: recipe for target 'iconv/lib/armeabi/libiconv.so' failed

### ISSUE THREAD

**Issue by suijingfeng** [pelya/commandergenius#91]
I can't follow up,  I run './changeAppSettings.sh -a',then the following error occurs:

Patching ../src/Accelerometer.java
Patching ../src/Advertisement.java
Patching ../src/Audio.java
Patching ../src/Clipboard.java
Patching ../src/CloudSave.java
Patching ../src/DataDownloader.java
Patching ../src/DummyService.java
Patching ../src/GLSurfaceView_SDL.java
Patching ../src/Globals.java
Patching ../src/Keycodes.java
Patching ../src/MainActivity.java
Patching ../src/RestartMainActivity.java
Patching ../src/Settings.java
Patching ../src/SettingsMenu.java
Patching ../src/SettingsMenuKeyboard.java
Patching ../src/SettingsMenuMisc.java
Patching ../src/SettingsMenuMouse.java
Patching ../src/Video.java
Patching ../src/XZInputStream.java
Patching project/AndroidManifest.xml
Patching project/src/Globals.java
Patching project/jni/Settings.mk
Patching strings.xml
Cleaning up dependencies
Copying app data files from project/jni/application/src/AndroidData to project/assets
Compiling prebuilt libraries
make: Entering directory '/home/suijingfeng/Android/commandergenius/project/jni'
cd iconv/src  && \
./build.sh  && \
for ARCH in armeabi armeabi-v7a x86 arm64-v8a x86_64; do  \
	mkdir -p ../lib/$ARCH ../include ; \
	cp -f $ARCH/libiconv.so $ARCH/libcharset.so ../lib/$ARCH/  ; \
	cp -f $ARCH/include/*.h ../include/  ; \
	mkdir -p ../../icuuc/lib/$ARCH ../../icuuc/include/unicode ../../icuuc/include/layout  ; \
	cp -f $ARCH/libicu*.a $ARCH/libharfbuzz.a ../../icuuc/lib/$ARCH/  ; \
	cp -f $ARCH/include/unicode/*.h ../../icuuc/include/unicode/  ; \
	cp -f $ARCH/include/layout/*.h ../../icuuc/include/layout/  ; \
	cp -f $ARCH/include/icu-le-hb/layout/*.h ../../icuuc/include/layout/  ; \
done
/bin/sh: 2: ./build.sh: not found
Makefile.prebuilt:21: recipe for target 'iconv/lib/armeabi/libiconv.so' failed
make: *** [iconv/lib/armeabi/libiconv.so] Error 127
make: Leaving directory '/home/suijingfeng/Android/commandergenius/project/jni'
Done

don't know how to handle this, any help would be appreciate, thanks

**Comment by tbaker4802** [comment]
you're missing build.sh or possibly its permissions are wrong... make sure
its executable

done
/bin/sh: 2: ./build.sh: not found



Timothy Baker
Chief Technology Officer
Online Mega Sellers Corp

**Comment by pelya** [comment]
Run

git submodule update --init --recursive

**Comment by pelya** [comment]
Google has removed support for armv5 in the latest NDK, I'll update build
scripts soon.

**Comment by pelya** [comment]
I've fixed build scripts, please run

git submodule update

then try to compile it again

**Comment by suijingfeng** [comment]
After I run,

$ git submodule update --init --recursive
fatal: reference is not a tree: 1407ec0e1775366aed527b6113dd14a02d046c09
Unable to checkout '1407ec0e1775366aed527b6113dd14a02d046c09' in submodule path 'project/jni/application/c-dogs/src/src/tests/cbehave/rlutil'
Failed to recurse into submodule path 'project/jni/application/c-dogs/src/src/tests/cbehave'
Cloning into 'GsKit'...
Username for 'https://github.com': suijingfeng
Password for 'https://suijingfeng@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/gerstrong/GsKit.git/' not found
fatal: clone of 'https://github.com/gerstrong/GsKit.git' into submodule path 'GsKit' failed

./changeAppSettings.sh -a
Patching ../src/Accelerometer.java
Patching ../src/Advertisement.java
Patching ../src/Audio.java
Patching ../src/Clipboard.java
Patching ../src/CloudSave.java
Patching ../src/DataDownloader.java
Patching ../src/DummyService.java
Patching ../src/GLSurfaceView_SDL.java
Patching ../src/Globals.java
Patching ../src/Keycodes.java
Patching ../src/MainActivity.java
Patching ../src/RestartMainActivity.java
Patching ../src/Settings.java
Patching ../src/SettingsMenu.java
Patching ../src/SettingsMenuKeyboard.java
Patching ../src/SettingsMenuMisc.java
Patching ../src/SettingsMenuMouse.java
Patching ../src/Video.java
Patching ../src/XZInputStream.java
Patching project/AndroidManifest.xml
Patching project/src/Globals.java
Patching project/jni/Settings.mk
Patching strings.xml
Cleaning up dependencies
Copying app data files from project/jni/application/src/AndroidData to project/assets
Compiling prebuilt libraries
make: Entering directory '/home/suijingfeng/Android/commandergenius/project/jni'
git submodule update --init --recursive
fatal: reference is not a tree: 1407ec0e1775366aed527b6113dd14a02d046c09
Unable to checkout '1407ec0e1775366aed527b6113dd14a02d046c09' in submodule path 'application/c-dogs/src/src/tests/cbehave/rlutil'
Failed to recurse into submodule path 'application/c-dogs/src/src/tests/cbehave'
Cloning into 'GsKit'...
Username for 'https://github.com':

**Comment by suijingfeng** [comment]
Thands a lot for helping, but i can not successful run `./changeAppSettings.sh -a`

libiconv-1.15/woe32dll/export.h
+ cd libiconv-1.15
+ cp -f /home/suijingfeng/Android/commandergenius/project/jni/iconv/src/config.sub build-aux/
+ cp -f /home/suijingfeng/Android/commandergenius/project/jni/iconv/src/config.guess build-aux/
+ cp -f /home/suijingfeng/Android/commandergenius/project/jni/iconv/src/config.sub libcharset/build-aux/
+ cp -f /home/suijingfeng/Android/commandergenius/project/jni/iconv/src/config.guess libcharset/build-aux/
+ sed -i,tmp s/MB_CUR_MAX/1/g lib/loop_wchar.h
+ pwd
+ env CFLAGS=-I/sources/android/support/include -D_IO_getc=getc LDFLAGS=-L/home/suijingfeng/Android/commandergenius/project/jni/iconv/src/arm64-v8a  /home/suijingfeng/Android/commandergenius/project/jni/iconv/src/setCrossEnvironment-arm64-v8a.sh ./configure --host=aarch64-linux-android --prefix=/home/suijingfeng/Android/commandergenius/project/jni/iconv/src/arm64-v8a/libiconv-1.15/.. --enable-static --enable-shared
dirname: missing operand
Try 'dirname --help' for more information.
readlink: missing operand
Try 'readlink --help' for more information.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for aarch64-linux-android-strip... /toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make sets $(MAKE)... (cached) yes
checking for aarch64-linux-android-gcc... /toolchains/llvm/prebuilt/linux-x86_64/bin/clang
checking whether the C compiler works... no
thanks a lot for helpin./changeAppSettings.sh -ag, but I still can not run 

configure: error: in `/home/suijingfeng/Android/commandergenius/project/jni/iconv/src/arm64-v8a/libiconv-1.15':
configure: error: C compiler cannot create executables
See `config.log' for more details
+ exit 1
Makefile.prebuilt:21: recipe for target 'iconv/lib/armeabi-v7a/libiconv.so' failed
make: *** [iconv/lib/armeabi-v7a/libiconv.so] Error 1
make: Leaving directory '/home/suijingfeng/Android/commandergenius/project/jni'
Done

**Comment by pelya** [comment]
What error does build.log in iconv directory show?

**Comment by suijingfeng** [comment]
sorry its my fault, not add the NDK environment to .bashrc

**Comment by suijingfeng** [comment]
Build is not successful: 

Failed to recurse into submodule path 'application/c-dogs/src/src/tests/cbehave'
Cloning into 'project/jni/application/commandergenius/commandergenius'...
remote: Counting objects: 64210, done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 64210 (delta 162), reused 237 (delta 118), pack-reused 63858
Receiving objects: 100% (64210/64210), 140.62 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (52763/52763), done.
Checking connectivity... done.
Submodule path 'application/commandergenius/commandergenius': checked out '5e9d2ef1d4f10d8a23c016e3ec010181faa2ba9e'
Submodule 'GsKit' (https://github.com/gerstrong/GsKit.git) registered for path '../../GsKit'
Cloning into 'GsKit'...
Username for 'https://github.com': suijingfeng
Password for 'https://suijingfeng@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/gerstrong/GsKit.git/' not found
fatal: clone of 'https://github.com/gerstrong/GsKit.git' into submodule path 'GsKit' failed
Failed to recurse into submodule path 'application/commandergenius/commandergenius'
Makefile.prebuilt:38: recipe for target 'iconv/src/build.sh' failed
make: *** [iconv/src/build.sh] Error 128
