### ISSUE TITLE
submodule issues

### ISSUE THREAD

**Issue by suijingfeng** [pelya/commandergenius#93]
Build is not successful:

Failed to recurse into submodule path 'application/c-dogs/src/src/tests/cbehave'
Cloning into 'project/jni/application/commandergenius/commandergenius'...
remote: Counting objects: 64210, done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 64210 (delta 162), reused 237 (delta 118), pack-reused 63858
Receiving objects: 100% (64210/64210), 140.62 MiB | 1.15 MiB/s, done.
Resolving deltas: 100% (52763/52763), done.
Checking connectivity... done.
Submodule path 'application/commandergenius/commandergenius': checked out '5e9d2ef1d4f10d8a23c016e3ec010181faa2ba9e'
Submodule 'GsKit' (https://github.com/gerstrong/GsKit.git) registered for path '../../GsKit'
Cloning into 'GsKit'...
Username for 'https://github.com': 
Password for 'https://suijingfeng@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/gerstrong/GsKit.git/' not found
fatal: clone of 'https://github.com/gerstrong/GsKit.git' into submodule path 'GsKit' failed
Failed to recurse into submodule path 'application/commandergenius/commandergenius'
Makefile.prebuilt:38: recipe for target 'iconv/src/build.sh' failed
make: *** [iconv/src/build.sh] Error 128

**Comment by pelya** [comment]
This submodule was removed. Update the repo, delete
project/jni/application/commandergenius/commandergenius/GsKit and
project/jni/application/c-dogs and run 'git submodule update' again

**Comment by suijingfeng** [comment]
thanks for you help, problem solved with your instructions
